<?php

/*
 *
 * This file part of WatermossMC.
 *
 *  __        __    _                                    __  __  ____
 *  \ \      / /_ _| |_ ___ _ __ _ __ ___   ___  ___ ___|  \/  |/ ___|
 *   \ \ /\ / / _` | __/ _ \ '__| '_ ` _ \ / _ \/ __/ __| |\/| | |
 *    \ V  V / (_| | ||  __/ |  | | | | | | (_) \__ \__ \ |  | | |___
 *     \_/\_/ \__,_|\__\___|_|  |_| |_| |_|\___/|___/___/_|  |_|\____|
 *
 * @author WatermossMC Team
 * @license Apache 2.0
 */

declare(strict_types=1);

namespace watermossmc\network\mcpe\protocol\types\command;

/**
 * This file is automatically generated; do NOT edit it by hand.
 * Regenerate it by running tools/generate-command-parameter-types.php
 */
final class CommandParameterTypes
{
	private function __construct()
	{
		//NOOP
	}

	public const INT = 1; // int
	public const VAL = 3; // float
	public const RVAL = 4; // value
	public const WILDCARDINT = 5; // wildcard int
	public const OPERATOR = 6; // operator
	public const COMPAREOPERATOR = 7; // compare operator
	public const SELECTION = 8; // target
	public const WILDCARDSELECTION = 10; // target
	public const PATHCOMMAND = 17; // filepath
	public const FULLINTEGERRANGE = 23; // integer range
	public const EQUIPMENTSLOTENUM = 47; // equipment slots
	public const ID = 56; // string
	public const POSITION = 64; // x y z
	public const POSITION_FLOAT = 65; // x y z
	public const MESSAGE_ROOT = 68; // message
	public const RAWTEXT = 70; // text
	public const JSON_OBJECT = 74; // json
	public const BLOCK_STATE_ARRAY = 84; // block states
	public const CODEBUILDERARGS = 87; // command
}
